### ISSUE TITLE
为什么config.yml文件里面的cmdWhitelist没有效果

### ISSUE THREAD

**Issue by szzz666** [MemoriesOfTime/GunWar#78]
为什么config.yml文件里面的cmdWhitelist没有效果
就是可以在游戏房间中使用的命令
![image](https://github.com/MemoriesOfTime/GunWar/assets/60167194/c4cd64f1-3b22-4a7a-befc-8ebbb105ae1e)

**Comment by lt-name** [comment]
请提供所使用的核心，插件版本
还有游戏内提示截图

**Comment by szzz666** [comment]
Nukkit PM1E 1.19.80.2770

![QQ截图20230603140947](https://github.com/MemoriesOfTime/GunWar/assets/60167194/226ac820-1fa4-4a6b-be5d-d196cfc83c0b)

**Comment by lt-name** [comment]
已修复，请更新到最新快照测试

**Comment by szzz666** [comment]
name yyds

**Comment by szzz666** [comment]
name 还有烫手山芋
